"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Card, Input, Select, Button, PageHeader, Spinner } from "@/components/ui";

export default function NewUserPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState<{ type: "success" | "error"; msg: string } | null>(null);
  const [successData, setSuccessData] = useState<{ usercode: string; bankNumber: string } | null>(null);
  const [form, setForm] = useState({
    firstname: "",
    lastname: "",
    email: "",
    password: "",
    balance: "0",
    currency: "USD",
    canTransfer: "true",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus(null);
    setSuccessData(null);
    setLoading(true);

    try {
      const res = await fetch("/api/admin/users/new", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          email: form.email,
          password: form.password,
          firstname: form.firstname,
          lastname: form.lastname,
          balance: parseFloat(form.balance) || 0,
          currency: form.currency,
          canTransfer: form.canTransfer === "true",
        }),
      });
      const data = await res.json();

      if (!res.ok) {
        setStatus({ type: "error", msg: data.error ?? "Something went wrong" });
        setLoading(false);
        return;
      }

      setSuccessData({ usercode: data.usercode ?? "—", bankNumber: data.bankNumber ?? "—" });
      setStatus({
        type: "success",
        msg: `User created successfully. Bank number and usercode are generated by the system.`,
      });
      setTimeout(() => router.push("/admin/users"), 2000);
    } catch (err) {
      setStatus({ type: "error", msg: "Request failed. Please try again." });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <PageHeader title="Create User" backHref="/admin/users" subtitle="Add a new user (bank number and usercode are auto-generated)" />
      <Card>
        <form onSubmit={handleSubmit} className="space-y-5 max-w-lg">
          {status && (
            <div
              className={`p-4 rounded-xl text-sm ${
                status.type === "success" ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-700"
              }`}
            >
              {status.msg}
              {successData && status.type === "success" && (
                <div className="mt-3 font-medium">
                  Usercode: <code className="bg-emerald-100 px-1.5 rounded">{successData.usercode}</code>
                  {" · "}
                  Bank #: <code className="bg-emerald-100 px-1.5 rounded">{successData.bankNumber}</code>
                </div>
              )}
            </div>
          )}
          <div className="grid sm:grid-cols-2 gap-5">
            <Input
              label="First Name"
              value={form.firstname}
              onChange={(e) => setForm({ ...form, firstname: e.target.value })}
              required
              disabled={loading}
            />
            <Input
              label="Last Name"
              value={form.lastname}
              onChange={(e) => setForm({ ...form, lastname: e.target.value })}
              required
              disabled={loading}
            />
          </div>
          <Input
            label="Email"
            type="email"
            value={form.email}
            onChange={(e) => setForm({ ...form, email: e.target.value })}
            required
            disabled={loading}
          />
          <Input
            label="Password"
            type="password"
            value={form.password}
            onChange={(e) => setForm({ ...form, password: e.target.value })}
            required
            placeholder="At least 6 characters"
            disabled={loading}
          />
          <div className="grid sm:grid-cols-2 gap-5">
            <Input
              label="Initial Balance"
              type="number"
              min="0"
              step="0.01"
              value={form.balance}
              onChange={(e) => setForm({ ...form, balance: e.target.value })}
              disabled={loading}
            />
            <Select
              label="Currency"
              value={form.currency}
              onChange={(e) => setForm({ ...form, currency: e.target.value })}
              options={[
                { value: "USD", label: "USD" },
                { value: "GBP", label: "GBP" },
                { value: "EUR", label: "EUR" },
              ]}
              disabled={loading}
            />
          </div>
          <Select
            label="Can Transfer"
            value={form.canTransfer}
            onChange={(e) => setForm({ ...form, canTransfer: e.target.value })}
            options={[
              { value: "true", label: "Yes" },
              { value: "false", label: "No" },
            ]}
            disabled={loading}
          />
          <div className="flex gap-2 pt-1">
            <Button type="submit" disabled={loading}>
              {loading ? (
                <>
                  <Spinner size="sm" className="mr-2" />
                  Creating…
                </>
              ) : (
                "Create User"
              )}
            </Button>
            <Button type="button" variant="outline" onClick={() => router.back()} disabled={loading}>
              Cancel
            </Button>
          </div>
        </form>
      </Card>
    </div>
  );
}
