export const CURRENCIES = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "GBP", name: "Pound Sterling", symbol: "£" },
  { code: "EUR", name: "Euro", symbol: "€" },
];

export const ROLES = ["member", "administrator", "super-admin"];

export const GENDERS = [
  { value: "", label: "— Select —" },
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
];

export const RELIGIONS = [
  { value: "", label: "— Select —" },
  { value: "christianity", label: "Christianity" },
  { value: "islam", label: "Islam" },
  { value: "judaism", label: "Judaism" },
  { value: "hinduism", label: "Hinduism" },
  { value: "buddhism", label: "Buddhism" },
  { value: "other", label: "Other" },
];

export const RELATIONSHIPS = [
  { value: "", label: "— Select —" },
  { value: "spouse", label: "Spouse" },
  { value: "parent", label: "Parent" },
  { value: "child", label: "Child" },
  { value: "sibling", label: "Sibling" },
  { value: "other", label: "Other" },
];

export const COUNTRIES = [
  { iso_2: "AF", name: "Afghanistan" },
  { iso_2: "AL", name: "Albania" },
  { iso_2: "DZ", name: "Algeria" },
  { iso_2: "AD", name: "Andorra" },
  { iso_2: "AO", name: "Angola" },
  { iso_2: "AG", name: "Antigua and Barbuda" },
  { iso_2: "AR", name: "Argentina" },
  { iso_2: "AM", name: "Armenia" },
  { iso_2: "AU", name: "Australia" },
  { iso_2: "AT", name: "Austria" },
  { iso_2: "AZ", name: "Azerbaijan" },
  { iso_2: "BS", name: "Bahamas" },
  { iso_2: "BH", name: "Bahrain" },
  { iso_2: "BD", name: "Bangladesh" },
  { iso_2: "BB", name: "Barbados" },
  { iso_2: "BY", name: "Belarus" },
  { iso_2: "BE", name: "Belgium" },
  { iso_2: "BZ", name: "Belize" },
  { iso_2: "BJ", name: "Benin" },
  { iso_2: "BT", name: "Bhutan" },
  { iso_2: "BO", name: "Bolivia" },
  { iso_2: "BA", name: "Bosnia and Herzegovina" },
  { iso_2: "BW", name: "Botswana" },
  { iso_2: "BR", name: "Brazil" },
  { iso_2: "BN", name: "Brunei" },
  { iso_2: "BG", name: "Bulgaria" },
  { iso_2: "BF", name: "Burkina Faso" },
  { iso_2: "BI", name: "Burundi" },
  { iso_2: "CV", name: "Cabo Verde" },
  { iso_2: "KH", name: "Cambodia" },
  { iso_2: "CM", name: "Cameroon" },
  { iso_2: "CA", name: "Canada" },
  { iso_2: "CF", name: "Central African Republic" },
  { iso_2: "TD", name: "Chad" },
  { iso_2: "CL", name: "Chile" },
  { iso_2: "CN", name: "China" },
  { iso_2: "CO", name: "Colombia" },
  { iso_2: "KM", name: "Comoros" },
  { iso_2: "CG", name: "Congo" },
  { iso_2: "CD", name: "Congo (Democratic Republic)" },
  { iso_2: "CR", name: "Costa Rica" },
  { iso_2: "CI", name: "Côte d'Ivoire" },
  { iso_2: "HR", name: "Croatia" },
  { iso_2: "CU", name: "Cuba" },
  { iso_2: "CY", name: "Cyprus" },
  { iso_2: "CZ", name: "Czech Republic" },
  { iso_2: "DK", name: "Denmark" },
  { iso_2: "DJ", name: "Djibouti" },
  { iso_2: "DM", name: "Dominica" },
  { iso_2: "DO", name: "Dominican Republic" },
  { iso_2: "EC", name: "Ecuador" },
  { iso_2: "EG", name: "Egypt" },
  { iso_2: "SV", name: "El Salvador" },
  { iso_2: "GQ", name: "Equatorial Guinea" },
  { iso_2: "ER", name: "Eritrea" },
  { iso_2: "EE", name: "Estonia" },
  { iso_2: "SZ", name: "Eswatini" },
  { iso_2: "ET", name: "Ethiopia" },
  { iso_2: "FJ", name: "Fiji" },
  { iso_2: "FI", name: "Finland" },
  { iso_2: "FR", name: "France" },
  { iso_2: "GA", name: "Gabon" },
  { iso_2: "GM", name: "Gambia" },
  { iso_2: "GE", name: "Georgia" },
  { iso_2: "DE", name: "Germany" },
  { iso_2: "GH", name: "Ghana" },
  { iso_2: "GR", name: "Greece" },
  { iso_2: "GD", name: "Grenada" },
  { iso_2: "GT", name: "Guatemala" },
  { iso_2: "GN", name: "Guinea" },
  { iso_2: "GW", name: "Guinea-Bissau" },
  { iso_2: "GY", name: "Guyana" },
  { iso_2: "HT", name: "Haiti" },
  { iso_2: "HN", name: "Honduras" },
  { iso_2: "HK", name: "Hong Kong" },
  { iso_2: "HU", name: "Hungary" },
  { iso_2: "IS", name: "Iceland" },
  { iso_2: "IN", name: "India" },
  { iso_2: "ID", name: "Indonesia" },
  { iso_2: "IR", name: "Iran" },
  { iso_2: "IQ", name: "Iraq" },
  { iso_2: "IE", name: "Ireland" },
  { iso_2: "IL", name: "Israel" },
  { iso_2: "IT", name: "Italy" },
  { iso_2: "JM", name: "Jamaica" },
  { iso_2: "JP", name: "Japan" },
  { iso_2: "JO", name: "Jordan" },
  { iso_2: "KZ", name: "Kazakhstan" },
  { iso_2: "KE", name: "Kenya" },
  { iso_2: "KI", name: "Kiribati" },
  { iso_2: "KP", name: "North Korea" },
  { iso_2: "KR", name: "South Korea" },
  { iso_2: "KW", name: "Kuwait" },
  { iso_2: "KG", name: "Kyrgyzstan" },
  { iso_2: "LA", name: "Laos" },
  { iso_2: "LV", name: "Latvia" },
  { iso_2: "LB", name: "Lebanon" },
  { iso_2: "LS", name: "Lesotho" },
  { iso_2: "LR", name: "Liberia" },
  { iso_2: "LY", name: "Libya" },
  { iso_2: "LI", name: "Liechtenstein" },
  { iso_2: "LT", name: "Lithuania" },
  { iso_2: "LU", name: "Luxembourg" },
  { iso_2: "MO", name: "Macau" },
  { iso_2: "MG", name: "Madagascar" },
  { iso_2: "MW", name: "Malawi" },
  { iso_2: "MY", name: "Malaysia" },
  { iso_2: "MV", name: "Maldives" },
  { iso_2: "ML", name: "Mali" },
  { iso_2: "MT", name: "Malta" },
  { iso_2: "MH", name: "Marshall Islands" },
  { iso_2: "MR", name: "Mauritania" },
  { iso_2: "MU", name: "Mauritius" },
  { iso_2: "MX", name: "Mexico" },
  { iso_2: "FM", name: "Micronesia" },
  { iso_2: "MD", name: "Moldova" },
  { iso_2: "MC", name: "Monaco" },
  { iso_2: "MN", name: "Mongolia" },
  { iso_2: "ME", name: "Montenegro" },
  { iso_2: "MA", name: "Morocco" },
  { iso_2: "MZ", name: "Mozambique" },
  { iso_2: "MM", name: "Myanmar" },
  { iso_2: "NA", name: "Namibia" },
  { iso_2: "NR", name: "Nauru" },
  { iso_2: "NP", name: "Nepal" },
  { iso_2: "NL", name: "Netherlands" },
  { iso_2: "NZ", name: "New Zealand" },
  { iso_2: "NI", name: "Nicaragua" },
  { iso_2: "NE", name: "Niger" },
  { iso_2: "NG", name: "Nigeria" },
  { iso_2: "MK", name: "North Macedonia" },
  { iso_2: "NO", name: "Norway" },
  { iso_2: "OM", name: "Oman" },
  { iso_2: "PK", name: "Pakistan" },
  { iso_2: "PW", name: "Palau" },
  { iso_2: "PS", name: "Palestine" },
  { iso_2: "PA", name: "Panama" },
  { iso_2: "PG", name: "Papua New Guinea" },
  { iso_2: "PY", name: "Paraguay" },
  { iso_2: "PE", name: "Peru" },
  { iso_2: "PH", name: "Philippines" },
  { iso_2: "PL", name: "Poland" },
  { iso_2: "PT", name: "Portugal" },
  { iso_2: "QA", name: "Qatar" },
  { iso_2: "RO", name: "Romania" },
  { iso_2: "RU", name: "Russia" },
  { iso_2: "RW", name: "Rwanda" },
  { iso_2: "KN", name: "Saint Kitts and Nevis" },
  { iso_2: "LC", name: "Saint Lucia" },
  { iso_2: "VC", name: "Saint Vincent and the Grenadines" },
  { iso_2: "WS", name: "Samoa" },
  { iso_2: "SM", name: "San Marino" },
  { iso_2: "ST", name: "São Tomé and Príncipe" },
  { iso_2: "SA", name: "Saudi Arabia" },
  { iso_2: "SN", name: "Senegal" },
  { iso_2: "RS", name: "Serbia" },
  { iso_2: "SC", name: "Seychelles" },
  { iso_2: "SL", name: "Sierra Leone" },
  { iso_2: "SG", name: "Singapore" },
  { iso_2: "SK", name: "Slovakia" },
  { iso_2: "SI", name: "Slovenia" },
  { iso_2: "SB", name: "Solomon Islands" },
  { iso_2: "SO", name: "Somalia" },
  { iso_2: "ZA", name: "South Africa" },
  { iso_2: "SS", name: "South Sudan" },
  { iso_2: "ES", name: "Spain" },
  { iso_2: "LK", name: "Sri Lanka" },
  { iso_2: "SD", name: "Sudan" },
  { iso_2: "SR", name: "Suriname" },
  { iso_2: "SE", name: "Sweden" },
  { iso_2: "CH", name: "Switzerland" },
  { iso_2: "SY", name: "Syria" },
  { iso_2: "TW", name: "Taiwan" },
  { iso_2: "TJ", name: "Tajikistan" },
  { iso_2: "TZ", name: "Tanzania" },
  { iso_2: "TH", name: "Thailand" },
  { iso_2: "TL", name: "Timor-Leste" },
  { iso_2: "TG", name: "Togo" },
  { iso_2: "TO", name: "Tonga" },
  { iso_2: "TT", name: "Trinidad and Tobago" },
  { iso_2: "TN", name: "Tunisia" },
  { iso_2: "TR", name: "Turkey" },
  { iso_2: "TM", name: "Turkmenistan" },
  { iso_2: "TV", name: "Tuvalu" },
  { iso_2: "UG", name: "Uganda" },
  { iso_2: "UA", name: "Ukraine" },
  { iso_2: "AE", name: "United Arab Emirates" },
  { iso_2: "GB", name: "United Kingdom" },
  { iso_2: "US", name: "United States" },
  { iso_2: "UY", name: "Uruguay" },
  { iso_2: "UZ", name: "Uzbekistan" },
  { iso_2: "VU", name: "Vanuatu" },
  { iso_2: "VA", name: "Vatican City" },
  { iso_2: "VE", name: "Venezuela" },
  { iso_2: "VN", name: "Vietnam" },
  { iso_2: "YE", name: "Yemen" },
  { iso_2: "ZM", name: "Zambia" },
  { iso_2: "ZW", name: "Zimbabwe" },
];
